//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="pull", Namespace="http://ws.epuap.gov.pl/pull/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OdpowiedzPullTyp))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ZapytaniePullTyp))]
public partial class pkPullService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback oczekujaceDokumentyOperationCompleted;
    
    private System.Threading.SendOrPostCallback pobierzNastepnyOperationCompleted;
    
    private System.Threading.SendOrPostCallback potwierdzOdebranieOperationCompleted;
    
    /// <remarks/>
    public pkPullService() {
        //this.Url = "https://ws.epuap.gov.pl:443/pk_external_ws/services/pull";
        this.Url = "https://int.epuap.gov.pl/pk_external_ws/services/pull";
    }

    /// <remarks/>
    public event oczekujaceDokumentyCompletedEventHandler oczekujaceDokumentyCompleted;
    
    /// <remarks/>
    public event pobierzNastepnyCompletedEventHandler pobierzNastepnyCompleted;
    
    /// <remarks/>
    public event potwierdzOdebranieCompletedEventHandler potwierdzOdebranieCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.epuap.gov.pl/pull/oczekujaceDokumenty", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("OdpowiedzPullOczekujace", Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public OdpowiedzPullOczekujaceTyp oczekujaceDokumenty([System.Xml.Serialization.XmlElementAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")] ZapytaniePullOczekujaceTyp ZapytaniePullOczekujace) {
        object[] results = this.Invoke("oczekujaceDokumenty", new object[] {
                    ZapytaniePullOczekujace});
        return ((OdpowiedzPullOczekujaceTyp)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginoczekujaceDokumenty(ZapytaniePullOczekujaceTyp ZapytaniePullOczekujace, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("oczekujaceDokumenty", new object[] {
                    ZapytaniePullOczekujace}, callback, asyncState);
    }
    
    /// <remarks/>
    public OdpowiedzPullOczekujaceTyp EndoczekujaceDokumenty(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OdpowiedzPullOczekujaceTyp)(results[0]));
    }
    
    /// <remarks/>
    public void oczekujaceDokumentyAsync(ZapytaniePullOczekujaceTyp ZapytaniePullOczekujace) {
        this.oczekujaceDokumentyAsync(ZapytaniePullOczekujace, null);
    }
    
    /// <remarks/>
    public void oczekujaceDokumentyAsync(ZapytaniePullOczekujaceTyp ZapytaniePullOczekujace, object userState) {
        if ((this.oczekujaceDokumentyOperationCompleted == null)) {
            this.oczekujaceDokumentyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnoczekujaceDokumentyOperationCompleted);
        }
        this.InvokeAsync("oczekujaceDokumenty", new object[] {
                    ZapytaniePullOczekujace}, this.oczekujaceDokumentyOperationCompleted, userState);
    }
    
    private void OnoczekujaceDokumentyOperationCompleted(object arg) {
        if ((this.oczekujaceDokumentyCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.oczekujaceDokumentyCompleted(this, new oczekujaceDokumentyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.epuap.gov.pl/pull/pobierzNastepny", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("OdpowiedzPullPobierz", Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public OdpowiedzPullPobierzTyp pobierzNastepny([System.Xml.Serialization.XmlElementAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")] ZapytaniePullPobierzTyp ZapytaniePullPobierz) {
        object[] results = this.Invoke("pobierzNastepny", new object[] {
                    ZapytaniePullPobierz});
        return ((OdpowiedzPullPobierzTyp)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginpobierzNastepny(ZapytaniePullPobierzTyp ZapytaniePullPobierz, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("pobierzNastepny", new object[] {
                    ZapytaniePullPobierz}, callback, asyncState);
    }
    
    /// <remarks/>
    public OdpowiedzPullPobierzTyp EndpobierzNastepny(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OdpowiedzPullPobierzTyp)(results[0]));
    }
    
    /// <remarks/>
    public void pobierzNastepnyAsync(ZapytaniePullPobierzTyp ZapytaniePullPobierz) {
        this.pobierzNastepnyAsync(ZapytaniePullPobierz, null);
    }
    
    /// <remarks/>
    public void pobierzNastepnyAsync(ZapytaniePullPobierzTyp ZapytaniePullPobierz, object userState) {
        if ((this.pobierzNastepnyOperationCompleted == null)) {
            this.pobierzNastepnyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpobierzNastepnyOperationCompleted);
        }
        this.InvokeAsync("pobierzNastepny", new object[] {
                    ZapytaniePullPobierz}, this.pobierzNastepnyOperationCompleted, userState);
    }
    
    private void OnpobierzNastepnyOperationCompleted(object arg) {
        if ((this.pobierzNastepnyCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.pobierzNastepnyCompleted(this, new pobierzNastepnyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.epuap.gov.pl/pull/potwierdzOdebranie", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("OdpowiedzPullPotwierdz", Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public OdpowiedzPullPotwierdzTyp potwierdzOdebranie([System.Xml.Serialization.XmlElementAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")] ZapytaniePullPotwierdzTyp ZapytaniePullPotwierdz) {
        object[] results = this.Invoke("potwierdzOdebranie", new object[] {
                    ZapytaniePullPotwierdz});
        return ((OdpowiedzPullPotwierdzTyp)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginpotwierdzOdebranie(ZapytaniePullPotwierdzTyp ZapytaniePullPotwierdz, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("potwierdzOdebranie", new object[] {
                    ZapytaniePullPotwierdz}, callback, asyncState);
    }
    
    /// <remarks/>
    public OdpowiedzPullPotwierdzTyp EndpotwierdzOdebranie(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OdpowiedzPullPotwierdzTyp)(results[0]));
    }
    
    /// <remarks/>
    public void potwierdzOdebranieAsync(ZapytaniePullPotwierdzTyp ZapytaniePullPotwierdz) {
        this.potwierdzOdebranieAsync(ZapytaniePullPotwierdz, null);
    }
    
    /// <remarks/>
    public void potwierdzOdebranieAsync(ZapytaniePullPotwierdzTyp ZapytaniePullPotwierdz, object userState) {
        if ((this.potwierdzOdebranieOperationCompleted == null)) {
            this.potwierdzOdebranieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpotwierdzOdebranieOperationCompleted);
        }
        this.InvokeAsync("potwierdzOdebranie", new object[] {
                    ZapytaniePullPotwierdz}, this.potwierdzOdebranieOperationCompleted, userState);
    }
    
    private void OnpotwierdzOdebranieOperationCompleted(object arg) {
        if ((this.potwierdzOdebranieCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.potwierdzOdebranieCompleted(this, new potwierdzOdebranieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class ZapytaniePullOczekujaceTyp : ZapytaniePullTyp {
}

/// <uwagi/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ZapytaniePullPotwierdzTyp))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ZapytaniePullPobierzTyp))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ZapytaniePullOczekujaceTyp))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class ZapytaniePullTyp {
    
    private string podmiotField;
    
    private string nazwaSkrytkiField;
    
    private string adresSkrytkiField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string podmiot {
        get {
            return this.podmiotField;
        }
        set {
            this.podmiotField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nazwaSkrytki {
        get {
            return this.nazwaSkrytkiField;
        }
        set {
            this.nazwaSkrytkiField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string adresSkrytki {
        get {
            return this.adresSkrytkiField;
        }
        set {
            this.adresSkrytkiField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class DokumentTyp {
    
    private string nazwaPlikuField;
    
    private string typPlikuField;
    
    private byte[] zawartoscField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nazwaPliku {
        get {
            return this.nazwaPlikuField;
        }
        set {
            this.nazwaPlikuField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string typPliku {
        get {
            return this.typPlikuField;
        }
        set {
            this.typPlikuField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] zawartosc {
        get {
            return this.zawartoscField;
        }
        set {
            this.zawartoscField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class DaneNadawcyTyp {
    
    private string uzytkownikField;
    
    private string systemField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string uzytkownik {
        get {
            return this.uzytkownikField;
        }
        set {
            this.uzytkownikField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string system {
        get {
            return this.systemField;
        }
        set {
            this.systemField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class DanePodmiotuTyp {
    
    private string identyfikatorField;
    
    private string typOsobyField;
    
    private string imieSkrotField;
    
    private string nazwiskoNazwaField;
    
    private string nipField;
    
    private string peselField;
    
    private string regonField;
    
    private bool zgodaField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string identyfikator {
        get {
            return this.identyfikatorField;
        }
        set {
            this.identyfikatorField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string typOsoby {
        get {
            return this.typOsobyField;
        }
        set {
            this.typOsobyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string imieSkrot {
        get {
            return this.imieSkrotField;
        }
        set {
            this.imieSkrotField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nazwiskoNazwa {
        get {
            return this.nazwiskoNazwaField;
        }
        set {
            this.nazwiskoNazwaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nip {
        get {
            return this.nipField;
        }
        set {
            this.nipField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pesel {
        get {
            return this.peselField;
        }
        set {
            this.peselField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string regon {
        get {
            return this.regonField;
        }
        set {
            this.regonField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool zgoda {
        get {
            return this.zgodaField;
        }
        set {
            this.zgodaField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class StatusTyp {
    
    private int kodField;
    
    private string komunikatField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int kod {
        get {
            return this.kodField;
        }
        set {
            this.kodField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string komunikat {
        get {
            return this.komunikatField;
        }
        set {
            this.komunikatField = value;
        }
    }
}

/// <uwagi/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OdpowiedzPullPotwierdzTyp))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OdpowiedzPullPobierzTyp))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OdpowiedzPullOczekujaceTyp))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class OdpowiedzPullTyp {
    
    private StatusTyp statusField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public StatusTyp status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class OdpowiedzPullPotwierdzTyp : OdpowiedzPullTyp {
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class OdpowiedzPullPobierzTyp : OdpowiedzPullTyp {
    
    private DanePodmiotuTyp danePodmiotuField;
    
    private DaneNadawcyTyp daneNadawcyField;
    
    private System.DateTime dataNadaniaField;
    
    private string nazwaSkrytkiField;
    
    private string adresSkrytkiField;
    
    private string adresOdpowiedziField;
    
    private bool czyTestoweField;
    
    private byte[] daneDodatkoweField;
    
    private DokumentTyp dokumentField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DanePodmiotuTyp danePodmiotu {
        get {
            return this.danePodmiotuField;
        }
        set {
            this.danePodmiotuField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DaneNadawcyTyp daneNadawcy {
        get {
            return this.daneNadawcyField;
        }
        set {
            this.daneNadawcyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dataNadania {
        get {
            return this.dataNadaniaField;
        }
        set {
            this.dataNadaniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nazwaSkrytki {
        get {
            return this.nazwaSkrytkiField;
        }
        set {
            this.nazwaSkrytkiField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string adresSkrytki {
        get {
            return this.adresSkrytkiField;
        }
        set {
            this.adresSkrytkiField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string adresOdpowiedzi {
        get {
            return this.adresOdpowiedziField;
        }
        set {
            this.adresOdpowiedziField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool czyTestowe {
        get {
            return this.czyTestoweField;
        }
        set {
            this.czyTestoweField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] daneDodatkowe {
        get {
            return this.daneDodatkoweField;
        }
        set {
            this.daneDodatkoweField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DokumentTyp dokument {
        get {
            return this.dokumentField;
        }
        set {
            this.dokumentField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class OdpowiedzPullOczekujaceTyp : OdpowiedzPullTyp {
    
    private int oczekujaceField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int oczekujace {
        get {
            return this.oczekujaceField;
        }
        set {
            this.oczekujaceField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class ZapytaniePullPotwierdzTyp : ZapytaniePullTyp {
    
    private string skrotField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string skrot {
        get {
            return this.skrotField;
        }
        set {
            this.skrotField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class ZapytaniePullPobierzTyp : ZapytaniePullTyp {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void oczekujaceDokumentyCompletedEventHandler(object sender, oczekujaceDokumentyCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class oczekujaceDokumentyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal oczekujaceDokumentyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OdpowiedzPullOczekujaceTyp Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OdpowiedzPullOczekujaceTyp)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void pobierzNastepnyCompletedEventHandler(object sender, pobierzNastepnyCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class pobierzNastepnyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal pobierzNastepnyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OdpowiedzPullPobierzTyp Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OdpowiedzPullPobierzTyp)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void potwierdzOdebranieCompletedEventHandler(object sender, potwierdzOdebranieCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class potwierdzOdebranieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal potwierdzOdebranieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OdpowiedzPullPotwierdzTyp Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OdpowiedzPullPotwierdzTyp)(this.results[0]));
        }
    }
}
